/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as AuthedAccountRouteImport } from './routes/_authed/account'
import { Route as AuthedAdminRouteImport } from './routes/_authed/admin'
import { Route as AuthedBookingsRouteImport } from './routes/_authed/bookings'
import { Route as AuthedDonateRouteImport } from './routes/_authed/donate'
import { Route as AuthedFavouritesRouteImport } from './routes/_authed/favourites'
import { Route as AuthedMessagesRouteImport } from './routes/_authed/messages'
import { Route as AuthedNotificationsRouteImport } from './routes/_authed/notifications'
import { Route as AuthedPeopleRouteImport } from './routes/_authed/people'
import { Route as AuthedResetPasswordRouteImport } from './routes/_authed/reset-password'
import { Route as AuthedVenuesRouteImport } from './routes/_authed/venues'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as AuthedMessagesUserIdRouteImport } from './routes/_authed/messages_.$userId'
import { Route as AuthedPeopleUserIdRouteImport } from './routes/_authed/people_.$userId'
import { Route as AuthedVenuesSlugRouteImport } from './routes/_authed/venues_.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedAccountRoute = AuthedAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAdminRoute = AuthedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedBookingsRoute = AuthedBookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedDonateRoute = AuthedDonateRouteImport.update({
  id: '/donate',
  path: '/donate',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedFavouritesRoute = AuthedFavouritesRouteImport.update({
  id: '/favourites',
  path: '/favourites',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedMessagesRoute = AuthedMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedNotificationsRoute = AuthedNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedPeopleRoute = AuthedPeopleRouteImport.update({
  id: '/people',
  path: '/people',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedResetPasswordRoute = AuthedResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedVenuesRoute = AuthedVenuesRouteImport.update({
  id: '/venues',
  path: '/venues',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedMessagesUserIdRoute = AuthedMessagesUserIdRouteImport.update({
  id: '/messages_/$userId',
  path: '/messages/$userId',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedPeopleUserIdRoute = AuthedPeopleUserIdRouteImport.update({
  id: '/people_/$userId',
  path: '/people/$userId',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedVenuesSlugRoute = AuthedVenuesSlugRouteImport.update({
  id: '/venues_/$slug',
  path: '/venues/$slug',
  getParentRoute: () => AuthedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/account': typeof AuthedAccountRoute
  '/admin': typeof AuthedAdminRoute
  '/bookings': typeof AuthedBookingsRoute
  '/donate': typeof AuthedDonateRoute
  '/favourites': typeof AuthedFavouritesRoute
  '/messages': typeof AuthedMessagesRoute
  '/notifications': typeof AuthedNotificationsRoute
  '/people': typeof AuthedPeopleRoute
  '/reset-password': typeof AuthedResetPasswordRoute
  '/venues': typeof AuthedVenuesRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/messages/$userId': typeof AuthedMessagesUserIdRoute
  '/people/$userId': typeof AuthedPeopleUserIdRoute
  '/venues/$slug': typeof AuthedVenuesSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/account': typeof AuthedAccountRoute
  '/admin': typeof AuthedAdminRoute
  '/bookings': typeof AuthedBookingsRoute
  '/donate': typeof AuthedDonateRoute
  '/favourites': typeof AuthedFavouritesRoute
  '/messages': typeof AuthedMessagesRoute
  '/notifications': typeof AuthedNotificationsRoute
  '/people': typeof AuthedPeopleRoute
  '/reset-password': typeof AuthedResetPasswordRoute
  '/venues': typeof AuthedVenuesRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/messages/$userId': typeof AuthedMessagesUserIdRoute
  '/people/$userId': typeof AuthedPeopleUserIdRoute
  '/venues/$slug': typeof AuthedVenuesSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/_authed/account': typeof AuthedAccountRoute
  '/_authed/admin': typeof AuthedAdminRoute
  '/_authed/bookings': typeof AuthedBookingsRoute
  '/_authed/donate': typeof AuthedDonateRoute
  '/_authed/favourites': typeof AuthedFavouritesRoute
  '/_authed/messages': typeof AuthedMessagesRoute
  '/_authed/notifications': typeof AuthedNotificationsRoute
  '/_authed/people': typeof AuthedPeopleRoute
  '/_authed/reset-password': typeof AuthedResetPasswordRoute
  '/_authed/venues': typeof AuthedVenuesRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/_authed/messages_/$userId': typeof AuthedMessagesUserIdRoute
  '/_authed/people_/$userId': typeof AuthedPeopleUserIdRoute
  '/_authed/venues_/$slug': typeof AuthedVenuesSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/account'
    | '/admin'
    | '/bookings'
    | '/donate'
    | '/favourites'
    | '/messages'
    | '/notifications'
    | '/people'
    | '/reset-password'
    | '/venues'
    | '/auth/callback'
    | '/messages/$userId'
    | '/people/$userId'
    | '/venues/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/account'
    | '/admin'
    | '/bookings'
    | '/donate'
    | '/favourites'
    | '/messages'
    | '/notifications'
    | '/people'
    | '/reset-password'
    | '/venues'
    | '/auth/callback'
    | '/messages/$userId'
    | '/people/$userId'
    | '/venues/$slug'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/_authed/account'
    | '/_authed/admin'
    | '/_authed/bookings'
    | '/_authed/donate'
    | '/_authed/favourites'
    | '/_authed/messages'
    | '/_authed/notifications'
    | '/_authed/people'
    | '/_authed/reset-password'
    | '/_authed/venues'
    | '/auth/callback'
    | '/_authed/messages_/$userId'
    | '/_authed/people_/$userId'
    | '/_authed/venues_/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRoute: typeof AuthedRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/account': {
      id: '/_authed/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AuthedAccountRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/admin': {
      id: '/_authed/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthedAdminRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/bookings': {
      id: '/_authed/bookings'
      path: '/bookings'
      fullPath: '/bookings'
      preLoaderRoute: typeof AuthedBookingsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/donate': {
      id: '/_authed/donate'
      path: '/donate'
      fullPath: '/donate'
      preLoaderRoute: typeof AuthedDonateRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/favourites': {
      id: '/_authed/favourites'
      path: '/favourites'
      fullPath: '/favourites'
      preLoaderRoute: typeof AuthedFavouritesRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/messages': {
      id: '/_authed/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof AuthedMessagesRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/notifications': {
      id: '/_authed/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AuthedNotificationsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/people': {
      id: '/_authed/people'
      path: '/people'
      fullPath: '/people'
      preLoaderRoute: typeof AuthedPeopleRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/reset-password': {
      id: '/_authed/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof AuthedResetPasswordRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/venues': {
      id: '/_authed/venues'
      path: '/venues'
      fullPath: '/venues'
      preLoaderRoute: typeof AuthedVenuesRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/messages_/$userId': {
      id: '/_authed/messages_/$userId'
      path: '/messages/$userId'
      fullPath: '/messages/$userId'
      preLoaderRoute: typeof AuthedMessagesUserIdRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/people_/$userId': {
      id: '/_authed/people_/$userId'
      path: '/people/$userId'
      fullPath: '/people/$userId'
      preLoaderRoute: typeof AuthedPeopleUserIdRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/venues_/$slug': {
      id: '/_authed/venues_/$slug'
      path: '/venues/$slug'
      fullPath: '/venues/$slug'
      preLoaderRoute: typeof AuthedVenuesSlugRouteImport
      parentRoute: typeof AuthedRoute
    }
  }
}

interface AuthedRouteChildren {
  AuthedAccountRoute: typeof AuthedAccountRoute
  AuthedAdminRoute: typeof AuthedAdminRoute
  AuthedBookingsRoute: typeof AuthedBookingsRoute
  AuthedDonateRoute: typeof AuthedDonateRoute
  AuthedFavouritesRoute: typeof AuthedFavouritesRoute
  AuthedMessagesRoute: typeof AuthedMessagesRoute
  AuthedNotificationsRoute: typeof AuthedNotificationsRoute
  AuthedPeopleRoute: typeof AuthedPeopleRoute
  AuthedResetPasswordRoute: typeof AuthedResetPasswordRoute
  AuthedVenuesRoute: typeof AuthedVenuesRoute
  AuthedMessagesUserIdRoute: typeof AuthedMessagesUserIdRoute
  AuthedPeopleUserIdRoute: typeof AuthedPeopleUserIdRoute
  AuthedVenuesSlugRoute: typeof AuthedVenuesSlugRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedAccountRoute: AuthedAccountRoute,
  AuthedAdminRoute: AuthedAdminRoute,
  AuthedBookingsRoute: AuthedBookingsRoute,
  AuthedDonateRoute: AuthedDonateRoute,
  AuthedFavouritesRoute: AuthedFavouritesRoute,
  AuthedMessagesRoute: AuthedMessagesRoute,
  AuthedNotificationsRoute: AuthedNotificationsRoute,
  AuthedPeopleRoute: AuthedPeopleRoute,
  AuthedResetPasswordRoute: AuthedResetPasswordRoute,
  AuthedVenuesRoute: AuthedVenuesRoute,
  AuthedMessagesUserIdRoute: AuthedMessagesUserIdRoute,
  AuthedPeopleUserIdRoute: AuthedPeopleUserIdRoute,
  AuthedVenuesSlugRoute: AuthedVenuesSlugRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRoute: AuthedRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  AuthCallbackRoute: AuthCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
