/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as GuidelinesRouteImport } from './routes/guidelines'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as AuthedAccountRouteImport } from './routes/_authed/account'
import { Route as AuthedAdminRouteImport } from './routes/_authed/admin'
import { Route as AuthedBookingsRouteImport } from './routes/_authed/bookings'
import { Route as AuthedDonateRouteImport } from './routes/_authed/donate'
import { Route as AuthedFavouritesRouteImport } from './routes/_authed/favourites'
import { Route as AuthedFeedRouteImport } from './routes/_authed/feed'
import { Route as AuthedMeetupsRouteImport } from './routes/_authed/meetups'
import { Route as AuthedMessagesRouteImport } from './routes/_authed/messages'
import { Route as AuthedNotificationsRouteImport } from './routes/_authed/notifications'
import { Route as AuthedPeopleRouteImport } from './routes/_authed/people'
import { Route as AuthedResetPasswordRouteImport } from './routes/_authed/reset-password'
import { Route as AuthedVenuesRouteImport } from './routes/_authed/venues'
import { Route as ApiBmcWebhookRouteImport } from './routes/api/bmc-webhook'
import { Route as ApiPushDispatchRouteImport } from './routes/api/push-dispatch'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as AuthedMeetupsMeetupIdRouteImport } from './routes/_authed/meetups_.$meetupId'
import { Route as AuthedMessagesUserIdRouteImport } from './routes/_authed/messages_.$userId'
import { Route as AuthedPeopleUserIdRouteImport } from './routes/_authed/people_.$userId'
import { Route as AuthedVenuesSlugRouteImport } from './routes/_authed/venues_.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidelinesRoute = GuidelinesRouteImport.update({
  id: '/guidelines',
  path: '/guidelines',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedAccountRoute = AuthedAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAdminRoute = AuthedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedBookingsRoute = AuthedBookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedDonateRoute = AuthedDonateRouteImport.update({
  id: '/donate',
  path: '/donate',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedFavouritesRoute = AuthedFavouritesRouteImport.update({
  id: '/favourites',
  path: '/favourites',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedFeedRoute = AuthedFeedRouteImport.update({
  id: '/feed',
  path: '/feed',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedMeetupsRoute = AuthedMeetupsRouteImport.update({
  id: '/meetups',
  path: '/meetups',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedMessagesRoute = AuthedMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedNotificationsRoute = AuthedNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedPeopleRoute = AuthedPeopleRouteImport.update({
  id: '/people',
  path: '/people',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedResetPasswordRoute = AuthedResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedVenuesRoute = AuthedVenuesRouteImport.update({
  id: '/venues',
  path: '/venues',
  getParentRoute: () => AuthedRoute,
} as any)
const ApiBmcWebhookRoute = ApiBmcWebhookRouteImport.update({
  id: '/api/bmc-webhook',
  path: '/api/bmc-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPushDispatchRoute = ApiPushDispatchRouteImport.update({
  id: '/api/push-dispatch',
  path: '/api/push-dispatch',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedMeetupsMeetupIdRoute = AuthedMeetupsMeetupIdRouteImport.update({
  id: '/meetups_/$meetupId',
  path: '/meetups/$meetupId',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedMessagesUserIdRoute = AuthedMessagesUserIdRouteImport.update({
  id: '/messages_/$userId',
  path: '/messages/$userId',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedPeopleUserIdRoute = AuthedPeopleUserIdRouteImport.update({
  id: '/people_/$userId',
  path: '/people/$userId',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedVenuesSlugRoute = AuthedVenuesSlugRouteImport.update({
  id: '/venues_/$slug',
  path: '/venues/$slug',
  getParentRoute: () => AuthedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/guidelines': typeof GuidelinesRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/register': typeof RegisterRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/account': typeof AuthedAccountRoute
  '/admin': typeof AuthedAdminRoute
  '/bookings': typeof AuthedBookingsRoute
  '/donate': typeof AuthedDonateRoute
  '/favourites': typeof AuthedFavouritesRoute
  '/feed': typeof AuthedFeedRoute
  '/meetups': typeof AuthedMeetupsRoute
  '/messages': typeof AuthedMessagesRoute
  '/notifications': typeof AuthedNotificationsRoute
  '/people': typeof AuthedPeopleRoute
  '/reset-password': typeof AuthedResetPasswordRoute
  '/venues': typeof AuthedVenuesRoute
  '/api/bmc-webhook': typeof ApiBmcWebhookRoute
  '/api/push-dispatch': typeof ApiPushDispatchRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/meetups/$meetupId': typeof AuthedMeetupsMeetupIdRoute
  '/messages/$userId': typeof AuthedMessagesUserIdRoute
  '/people/$userId': typeof AuthedPeopleUserIdRoute
  '/venues/$slug': typeof AuthedVenuesSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/guidelines': typeof GuidelinesRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/register': typeof RegisterRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/account': typeof AuthedAccountRoute
  '/admin': typeof AuthedAdminRoute
  '/bookings': typeof AuthedBookingsRoute
  '/donate': typeof AuthedDonateRoute
  '/favourites': typeof AuthedFavouritesRoute
  '/feed': typeof AuthedFeedRoute
  '/meetups': typeof AuthedMeetupsRoute
  '/messages': typeof AuthedMessagesRoute
  '/notifications': typeof AuthedNotificationsRoute
  '/people': typeof AuthedPeopleRoute
  '/reset-password': typeof AuthedResetPasswordRoute
  '/venues': typeof AuthedVenuesRoute
  '/api/bmc-webhook': typeof ApiBmcWebhookRoute
  '/api/push-dispatch': typeof ApiPushDispatchRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/meetups/$meetupId': typeof AuthedMeetupsMeetupIdRoute
  '/messages/$userId': typeof AuthedMessagesUserIdRoute
  '/people/$userId': typeof AuthedPeopleUserIdRoute
  '/venues/$slug': typeof AuthedVenuesSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/guidelines': typeof GuidelinesRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/register': typeof RegisterRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/_authed/account': typeof AuthedAccountRoute
  '/_authed/admin': typeof AuthedAdminRoute
  '/_authed/bookings': typeof AuthedBookingsRoute
  '/_authed/donate': typeof AuthedDonateRoute
  '/_authed/favourites': typeof AuthedFavouritesRoute
  '/_authed/feed': typeof AuthedFeedRoute
  '/_authed/meetups': typeof AuthedMeetupsRoute
  '/_authed/messages': typeof AuthedMessagesRoute
  '/_authed/notifications': typeof AuthedNotificationsRoute
  '/_authed/people': typeof AuthedPeopleRoute
  '/_authed/reset-password': typeof AuthedResetPasswordRoute
  '/_authed/venues': typeof AuthedVenuesRoute
  '/api/bmc-webhook': typeof ApiBmcWebhookRoute
  '/api/push-dispatch': typeof ApiPushDispatchRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/_authed/meetups_/$meetupId': typeof AuthedMeetupsMeetupIdRoute
  '/_authed/messages_/$userId': typeof AuthedMessagesUserIdRoute
  '/_authed/people_/$userId': typeof AuthedPeopleUserIdRoute
  '/_authed/venues_/$slug': typeof AuthedVenuesSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/guidelines'
    | '/login'
    | '/privacy'
    | '/register'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/terms'
    | '/account'
    | '/admin'
    | '/bookings'
    | '/donate'
    | '/favourites'
    | '/feed'
    | '/meetups'
    | '/messages'
    | '/notifications'
    | '/people'
    | '/reset-password'
    | '/venues'
    | '/api/bmc-webhook'
    | '/api/push-dispatch'
    | '/auth/callback'
    | '/meetups/$meetupId'
    | '/messages/$userId'
    | '/people/$userId'
    | '/venues/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/guidelines'
    | '/login'
    | '/privacy'
    | '/register'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/terms'
    | '/account'
    | '/admin'
    | '/bookings'
    | '/donate'
    | '/favourites'
    | '/feed'
    | '/meetups'
    | '/messages'
    | '/notifications'
    | '/people'
    | '/reset-password'
    | '/venues'
    | '/api/bmc-webhook'
    | '/api/push-dispatch'
    | '/auth/callback'
    | '/meetups/$meetupId'
    | '/messages/$userId'
    | '/people/$userId'
    | '/venues/$slug'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/forgot-password'
    | '/guidelines'
    | '/login'
    | '/privacy'
    | '/register'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/terms'
    | '/_authed/account'
    | '/_authed/admin'
    | '/_authed/bookings'
    | '/_authed/donate'
    | '/_authed/favourites'
    | '/_authed/feed'
    | '/_authed/meetups'
    | '/_authed/messages'
    | '/_authed/notifications'
    | '/_authed/people'
    | '/_authed/reset-password'
    | '/_authed/venues'
    | '/api/bmc-webhook'
    | '/api/push-dispatch'
    | '/auth/callback'
    | '/_authed/meetups_/$meetupId'
    | '/_authed/messages_/$userId'
    | '/_authed/people_/$userId'
    | '/_authed/venues_/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRoute: typeof AuthedRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  GuidelinesRoute: typeof GuidelinesRoute
  LoginRoute: typeof LoginRoute
  PrivacyRoute: typeof PrivacyRoute
  RegisterRoute: typeof RegisterRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
  ApiBmcWebhookRoute: typeof ApiBmcWebhookRoute
  ApiPushDispatchRoute: typeof ApiPushDispatchRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guidelines': {
      id: '/guidelines'
      path: '/guidelines'
      fullPath: '/guidelines'
      preLoaderRoute: typeof GuidelinesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/account': {
      id: '/_authed/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AuthedAccountRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/admin': {
      id: '/_authed/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthedAdminRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/bookings': {
      id: '/_authed/bookings'
      path: '/bookings'
      fullPath: '/bookings'
      preLoaderRoute: typeof AuthedBookingsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/donate': {
      id: '/_authed/donate'
      path: '/donate'
      fullPath: '/donate'
      preLoaderRoute: typeof AuthedDonateRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/favourites': {
      id: '/_authed/favourites'
      path: '/favourites'
      fullPath: '/favourites'
      preLoaderRoute: typeof AuthedFavouritesRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/feed': {
      id: '/_authed/feed'
      path: '/feed'
      fullPath: '/feed'
      preLoaderRoute: typeof AuthedFeedRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/meetups': {
      id: '/_authed/meetups'
      path: '/meetups'
      fullPath: '/meetups'
      preLoaderRoute: typeof AuthedMeetupsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/messages': {
      id: '/_authed/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof AuthedMessagesRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/notifications': {
      id: '/_authed/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AuthedNotificationsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/people': {
      id: '/_authed/people'
      path: '/people'
      fullPath: '/people'
      preLoaderRoute: typeof AuthedPeopleRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/reset-password': {
      id: '/_authed/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof AuthedResetPasswordRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/venues': {
      id: '/_authed/venues'
      path: '/venues'
      fullPath: '/venues'
      preLoaderRoute: typeof AuthedVenuesRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/api/bmc-webhook': {
      id: '/api/bmc-webhook'
      path: '/api/bmc-webhook'
      fullPath: '/api/bmc-webhook'
      preLoaderRoute: typeof ApiBmcWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/push-dispatch': {
      id: '/api/push-dispatch'
      path: '/api/push-dispatch'
      fullPath: '/api/push-dispatch'
      preLoaderRoute: typeof ApiPushDispatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/meetups_/$meetupId': {
      id: '/_authed/meetups_/$meetupId'
      path: '/meetups/$meetupId'
      fullPath: '/meetups/$meetupId'
      preLoaderRoute: typeof AuthedMeetupsMeetupIdRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/messages_/$userId': {
      id: '/_authed/messages_/$userId'
      path: '/messages/$userId'
      fullPath: '/messages/$userId'
      preLoaderRoute: typeof AuthedMessagesUserIdRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/people_/$userId': {
      id: '/_authed/people_/$userId'
      path: '/people/$userId'
      fullPath: '/people/$userId'
      preLoaderRoute: typeof AuthedPeopleUserIdRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/venues_/$slug': {
      id: '/_authed/venues_/$slug'
      path: '/venues/$slug'
      fullPath: '/venues/$slug'
      preLoaderRoute: typeof AuthedVenuesSlugRouteImport
      parentRoute: typeof AuthedRoute
    }
  }
}

interface AuthedRouteChildren {
  AuthedAccountRoute: typeof AuthedAccountRoute
  AuthedAdminRoute: typeof AuthedAdminRoute
  AuthedBookingsRoute: typeof AuthedBookingsRoute
  AuthedDonateRoute: typeof AuthedDonateRoute
  AuthedFavouritesRoute: typeof AuthedFavouritesRoute
  AuthedFeedRoute: typeof AuthedFeedRoute
  AuthedMeetupsRoute: typeof AuthedMeetupsRoute
  AuthedMessagesRoute: typeof AuthedMessagesRoute
  AuthedNotificationsRoute: typeof AuthedNotificationsRoute
  AuthedPeopleRoute: typeof AuthedPeopleRoute
  AuthedResetPasswordRoute: typeof AuthedResetPasswordRoute
  AuthedVenuesRoute: typeof AuthedVenuesRoute
  AuthedMeetupsMeetupIdRoute: typeof AuthedMeetupsMeetupIdRoute
  AuthedMessagesUserIdRoute: typeof AuthedMessagesUserIdRoute
  AuthedPeopleUserIdRoute: typeof AuthedPeopleUserIdRoute
  AuthedVenuesSlugRoute: typeof AuthedVenuesSlugRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedAccountRoute: AuthedAccountRoute,
  AuthedAdminRoute: AuthedAdminRoute,
  AuthedBookingsRoute: AuthedBookingsRoute,
  AuthedDonateRoute: AuthedDonateRoute,
  AuthedFavouritesRoute: AuthedFavouritesRoute,
  AuthedFeedRoute: AuthedFeedRoute,
  AuthedMeetupsRoute: AuthedMeetupsRoute,
  AuthedMessagesRoute: AuthedMessagesRoute,
  AuthedNotificationsRoute: AuthedNotificationsRoute,
  AuthedPeopleRoute: AuthedPeopleRoute,
  AuthedResetPasswordRoute: AuthedResetPasswordRoute,
  AuthedVenuesRoute: AuthedVenuesRoute,
  AuthedMeetupsMeetupIdRoute: AuthedMeetupsMeetupIdRoute,
  AuthedMessagesUserIdRoute: AuthedMessagesUserIdRoute,
  AuthedPeopleUserIdRoute: AuthedPeopleUserIdRoute,
  AuthedVenuesSlugRoute: AuthedVenuesSlugRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRoute: AuthedRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  GuidelinesRoute: GuidelinesRoute,
  LoginRoute: LoginRoute,
  PrivacyRoute: PrivacyRoute,
  RegisterRoute: RegisterRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
  ApiBmcWebhookRoute: ApiBmcWebhookRoute,
  ApiPushDispatchRoute: ApiPushDispatchRoute,
  AuthCallbackRoute: AuthCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
